[include ./MACROS/shared.conf]


#---------------------------------------------------------------------------------------------- FILAMENT SENSOR -------------------------------------------------------------------------------------


[filament_motion_sensor filament_sensor]
detection_length: 10
extruder: extruder

switch_pin: ^!PD2

pause_on_runout: True

runout_gcode:
    PRINT MSG="Runout Detected"

insert_gcode:
    PRINT MSG="Insert Detected"





#---------------------------------------------------------------------------------------------- RETRACTION -------------------------------------------------------------------------------------




[firmware_retraction]
retract_length: 4
#   The length of filament (in mm) to retract when G10 is activated,
#   and to unretract when G11 is activated (but see
#   unretract_extra_length below). The default is 0 mm.

retract_speed: 45
#   The speed of retraction, in mm/s. The default is 20 mm/s.


unretract_speed: 35
#   The speed of unretraction, in mm/s. The default is 10 mm/s.














